# Generated by Django 5.1.4 on 2024-12-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('crime_rate', models.FloatField()),
                ('crime_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('employed', models.BooleanField(default=False)),
                ('income', models.FloatField(default=0.0)),
                ('tax_contributions', models.FloatField(default=0.0)),
                ('reoffended', models.BooleanField(default=False)),
                ('sobriety_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
